#ifndef __NWAY_GATEWAY_XML_OP_NETWORK_COMMAND_H__
#define __NWAY_GATEWAY_XML_OP_NETWORK_COMMAND_H__
#define GXOP_CMD_LENGTH 7
#define GXOP_CMD_BASE 10030
#define GXOP_CMD_GET_GATEWAYS_REQ GXOP_CMD_BASE+1
#define GXOP_CMD_GET_GATEWAYS_RSP GXOP_CMD_BASE+2

#define GXOP_CMD_GET_GATEWAY_REQ  GXOP_CMD_BASE+3
#define GXOP_CMD_GET_GATEWAY_RSP  GXOP_CMD_BASE+4

#define GXOP_CMD_GET_GATEWAY_ADD_REQ GXOP_CMD_BASE+5
#define GXOP_CMD_GET_GATEWAY_ADD_RSP GXOP_CMD_BASE+6

#define GXOP_CMD_GET_GATEWAY_EDIT_REQ GXOP_CMD_BASE+7
#define GXOP_CMD_GET_GATEWAY_EDIT_RSP GXOP_CMD_BASE+8

#define GXOP_CMD_GET_GATEWAY_ERASE_REQ GXOP_CMD_BASE+9
#define GXOP_CMD_GET_GATEWAY_ERASE_RSP GXOP_CMD_BASE+10

#define GXOP_CMD_GET_GATEWAY_UNKOWN_REQ GXOP_CMD_BASE+11
#define GXOP_CMD_GET_GATEWAY_UNKOWN_RSP GXOP_CMD_BASE+12

#define GXOP_CMD_GET_GATEWAY_RELOAD_REQ GXOP_CMD_BASE+13
#define GXOP_CMD_GET_GATEWAY_RELOAD_RSP GXOP_CMD_BASE+14

#endif