# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: head.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='head.proto',
  package='nway_fs_opterator',
  serialized_pb=_b('\n\nhead.proto\x12\x11nway_fs_opterator\"A\n\x07MsgHead\x12\x0f\n\x07\x63ommand\x18\x01 \x02(\x05\x12\x13\n\x0bnway_length\x18\x02 \x02(\x05\x12\x10\n\x08\x63md_flag\x18\x03 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MSGHEAD = _descriptor.Descriptor(
  name='MsgHead',
  full_name='nway_fs_opterator.MsgHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='nway_fs_opterator.MsgHead.command', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nway_length', full_name='nway_fs_opterator.MsgHead.nway_length', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd_flag', full_name='nway_fs_opterator.MsgHead.cmd_flag', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['MsgHead'] = _MSGHEAD

MsgHead = _reflection.GeneratedProtocolMessageType('MsgHead', (_message.Message,), dict(
  DESCRIPTOR = _MSGHEAD,
  __module__ = 'head_pb2'
  # @@protoc_insertion_point(class_scope:nway_fs_opterator.MsgHead)
  ))
_sym_db.RegisterMessage(MsgHead)


# @@protoc_insertion_point(module_scope)
